spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:32770}/${DB_NAME:game_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:${env.OPENAI_API_KEY}}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

openai:
  api:
    gpt:
      model: ${GPT_VERSION:gpt-4o-mini}
      max-completion-tokens: ${MAX_COMPLETION_TOKENS:150}
server:
  port: ${SERVER_PORT:8082}