spring:
  profiles:
    active: dev

application:
  services:
    authentication:
      base-url: ${AUTH_SERVICE_HOST:http://localhost}:${AUTH_SERVICE_PORT:8080}
    game:
      base-url: ${GAME_SERVICE_HOST:http://localhost}:${GAME_SERVICE_PORT:8082}

jwt:
  secret: ${JWT_SECRET:${env.JWT_SECRET}}

server:
  port: ${SERVER_PORT:8085}