spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:32768}/${DB_NAME:user_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: auth-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'org.example.DTOs'

jwt:
  secret: ${JWT_SECRET:${env.JWT_SECRET}}

server:
  port: ${SERVER_PORT:8080}