services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    ports:
      - "32768:5432"
    networks:
      - "my-app-network"

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - "my-app-network"

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
        - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - "my-app-network"

  auth-service:
    build:
      context: ./authentication-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - "my-app-network"

  mail-service:
    build:
      context: ./mail-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - "my-app-network"

networks:
  my-app-network:
    driver: bridge