spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:32769}/${DB_NAME:mail_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: mail-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'org.example.DTOs'

application:
  services:
    authentication:
      baseUrl:  ${AUTH_SERVICE_HOST:http://localhost}:${AUTH_SERVICE_PORT:8085}

server:
  port: ${SERVER_PORT:8081}