apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: mstitel0/auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: user-database
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: user_db
            - name: DB_USERNAME
              value: admin
            - name: DB_PASSWORD
              value: admin
            - name: KAFKA_HOST
              value: my-kafka
            - name: KAFKA_PORT
              value: "9092"
            - name: SERVER_PORT
              value: "8080"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: JWT_SECRET


---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
