apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: mstitel0/mail-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: mail-database
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: mail_db
            - name: DB_USERNAME
              value: admin
            - name: DB_PASSWORD
              value: admin
            - name: KAFKA_HOST
              value: my-kafka
            - name: KAFKA_PORT
              value: "9092"
            - name: AUTH_SERVICE_HOST
              value: "http://localhost"
            - name: AUTH_SERVICE_PORT
              value: "8080"
            - name: SERVER_PORT
              value: "8081"
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: MAIL_PORT
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: MAIL_PASSWORD
            - name: MAIL_AUTH
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: MAIL_AUTH
            - name: MAIL_STARTTLS
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: MAIL_STARTTLS

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - protocol: TCP
      port: 8081
  type: ClusterIP
